### ISSUE TITLE
[Bug] Exp Dupe Bug

### ISSUE THREAD

**Issue by mVtZWFu** [math0898/OfflinePlayers#7]
**Describe the bug**
Player kill Exp 2x Dupe Bug

**To Reproduce**
1. Has exp
2. Log out
3. Kill Clone
4. Pick up experience
5. Check Exp

**Information to investigate**
- 1.20.1
- [ Offlineplayers Log](https://pastebin.com/X7z1QrYt)
- Purpur
- Original and Fork
- Which version of OfflinePlayers and LibsDisguises
- [Your config.yml file](https://pastebin.com/ZLgMVE0i)

**Comment by mVtZWFu** [comment]
Even if the target has 0 exp, killing Clone will increase level by 509.

It doesn't matter if the has exp or not.

**Comment by math0898** [comment]
It looks like xp is correctly being removed from the player when they rejoin. There could be an issue with how the xp value to be rewarded is determined (Essentially just clones dropping wayy too much xp). I'll do some testing and see if I can't get a fix done today.

**Comment by math0898** [comment]
I've been able to confirm the plugin is working as expected. 

Checking your logs, did you log out after killing the player? Then a clone spawned for them?

**Comment by mVtZWFu** [comment]
I logged out and killed the clone that was created.

**Comment by math0898** [comment]
Ok, thanks! If the player was dead a clone probably shouldn't have been created. I'll work on a fix for that bug.
